@host=http://localhost:5218

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jondoe@gmail.com",
    "username": "jondoe",
    "password": "123456"
}