@host=http://localhost:5218
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEb21haW4uVXNlckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6Ijc2YTUyYmViLWUwMGQtNGM4Zi05MzdjLTVkMjMxMzkwMjliYSIsImV4cCI6MTY4NjkxMTU3NiwiaXNzIjoiR3JlZW5UdWJlIiwiYXVkIjoiR3JlZW5UdWJlIn0.AQlTdqDKfNeIiIwoXDk8xnNSTzNOr4Eg42q0JZfq3VI
@userId=22c48d1b-0dbd-427c-b64c-f35b3c72722d

POST {{host}}/transactions/credit/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{   
    "TxId": "",
    "type": "deposit",
    "amount": 10
}

#"9999c9f9-9f99-99e9-b99c-b99cb99f9b99"